### ISSUE TITLE
Fejl ved load

### ISSUE THREAD

**Issue by sophiemba** [regiongis/erhvervsinfo#9]
Siden loader ikke. 

Skyldes dette flyt til ny url? 

![2019-03-12_09h27_00](https://user-images.githubusercontent.com/14992486/54185357-1987c200-44a9-11e9-8238-3e8d63a203f2.png)

**Comment by danielarnason** [comment]
@sophiemba Det ligner, at det er noget bøvl med et eller andet certifikat. Jeg mener, at vi har oplevet det tidligere. Jeg tror, at det er Mag og/eller Martin Høgh, som skal kontaktes til at fikse det her. 

@ClockEnd Er det noget du kan gøre? Jeg er på ferie i den her uge 😎

**Comment by danielarnason** [comment]
Den er vist løst nu.
